context:
  version: "0.59.0"

package:
  name: xan
  version: ${{ version }}

source:
  url: https://github.com/medialab/xan/archive/refs/tags/${{ version }}.tar.gz
  sha256: b2c101c85fb1b0e98f80aa2117e93c5381cc6483e199cbe6796da4a275511e20

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
      - if: unix
        then:
          - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions
          - $PREFIX/bin/xan completions zsh > $PREFIX/share/zsh/site-functions/_xan
          - $PREFIX/bin/xan completions bash > $PREFIX/share/bash-completion/completions/xan

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - xan --help
  - package_contents:
      bin:
        - xan
      files:
        - if: unix
          then:
            - share/bash-completion/completions/xan
            - share/zsh/site-functions/_xan
      strict: true

about:
  homepage: https://github.com/medialab/xan
  repository: https://github.com/medialab/xan
  documentation: https://github.com/medialab/xan
  summary: The CSV magician
  description: |
    xan is a command line tool that can be used to process CSV files directly
    from the shell. It has been written in Rust to be as fast as possible, use
    as little memory as possible, and can easily handle very large CSV files
    (Gigabytes). It is also able to leverage parallelism (through multithreading)
    to make some tasks complete as fast as your computer can allow. It can easily
    preview, filter, slice, aggregate, sort, join CSV files, and exposes a large
    collection of composable commands that can be chained together to perform a
    wide variety of typical tasks. xan also leverages its own expression language
    so you can perform complex tasks that cannot be done by relying on the
    simplest commands. This minimalistic language has been tailored for CSV data
    and is faster than evaluating typical dynamically-typed languages such as
    Python, Lua, JavaScript etc.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - Yomguithereal
    - apcamargo
    - rvalieris
